// All data sourced from ACLED, Al Jazeera, CFR, and Xinhua reporting.
// Campaign = Operation Roaring Lion (Israel) / Operation Epic Fury (US), Feb 28, 2026 onwards.

export type Initiator = 'USA' | 'Israel' | 'Iran' | 'Hezbollah';

export interface Strike {
  id: number;
  name: string;
  lat: number;
  lng: number;
  date: string;
  initiator: Initiator;
  target: string;
  description: string;
  estimatedKIA?: number;
  kiaNote?: string;
}

export const strikes: Strike[] = [

  // ── US / ISRAEL JOINT STRIKES ON IRAN ─────────────────────────────────────

  {
    id: 1,
    name: 'Khamenei compound, Tehran',
    lat: 35.73,
    lng: 51.43,
    date: 'Feb 28, 2026',
    initiator: 'USA',
    target: 'Supreme Leader\'s compound, north Tehran',
    description: 'Opening strike of Operation Roaring Lion / Epic Fury. The compound of Supreme Leader Ali Khamenei was destroyed. Trump confirmed Khamenei\'s death late Saturday afternoon. Several senior IRGC commanders and officials also killed in coordinated strikes on government facilities.',
    estimatedKIA: undefined,
    kiaNote: 'Khamenei killed. Additional senior officials killed; total leadership casualty count not confirmed.',
  },
  {
    id: 2,
    name: 'Ministry of Defence & Ministry of Intelligence, Tehran',
    lat: 35.69,
    lng: 51.39,
    date: 'Feb 28, 2026',
    initiator: 'USA',
    target: 'Ministry of Defence, Ministry of Intelligence, Atomic Energy Organization HQ — central Tehran',
    description: 'Multiple government ministry buildings struck including the Ministry of Defence, Intelligence, and Iran\'s Atomic Energy Organization headquarters. State broadcasting HQ also hit. A nearby school was struck with at least 2 students killed.',
    estimatedKIA: 2,
    kiaNote: '2 students killed in adjacent school strike. Government personnel casualties unconfirmed.',
  },
  {
    id: 3,
    name: 'Parchin military complex, Tehran',
    lat: 35.52,
    lng: 51.77,
    date: 'Feb 28, 2026',
    initiator: 'USA',
    target: 'Parchin military R&D complex — missile and drone production',
    description: 'Parchin, a key IRGC facility used for solid-fuel rocket development and drone production, was heavily struck in the opening salvo. Part of a broader effort to degrade Iran\'s missile manufacturing capacity.',
    estimatedKIA: undefined,
    kiaNote: 'Casualties not confirmed.',
  },
  {
    id: 4,
    name: 'Isfahan — nuclear & missile production facilities',
    lat: 32.65,
    lng: 51.67,
    date: 'Feb 28, 2026',
    initiator: 'USA',
    target: 'Isfahan uranium conversion facility & ballistic missile production hub',
    description: 'Isfahan, Iran\'s ballistic missile production hub and home to the uranium conversion facility (UCF), was struck in the opening wave. ACLED notes Isfahan as a primary target in the 350+ airstrike campaign.',
    estimatedKIA: undefined,
    kiaNote: 'Casualties not publicly confirmed.',
  },
  {
    id: 5,
    name: 'Fordow / Qom nuclear facility',
    lat: 34.85,
    lng: 50.60,
    date: 'Feb 28, 2026',
    initiator: 'USA',
    target: 'Fordow underground uranium enrichment facility, near Qom',
    description: 'The hardened underground Fordow enrichment facility near Qom was targeted with US bunker-buster munitions. Trump claimed "complete obliteration" of Iran\'s nuclear facilities; independent assessments said significant but not total destruction.',
    estimatedKIA: undefined,
    kiaNote: 'Casualties not publicly confirmed.',
  },
  {
    id: 6,
    name: 'Karaj — air defense and IRGC bases',
    lat: 35.84,
    lng: 50.94,
    date: 'Feb 28, 2026',
    initiator: 'USA',
    target: 'IRGC bases and air defense systems, Karaj (Alborz province)',
    description: 'Part of the systematic suppression of Iran\'s integrated air defense network. ACLED recorded ~200 air defense systems destroyed across Iran during the campaign.',
    estimatedKIA: undefined,
    kiaNote: 'Casualties not confirmed.',
  },
  {
    id: 7,
    name: 'Kermanshah — IRGC missile battalions',
    lat: 34.31,
    lng: 47.07,
    date: 'Feb 28, 2026',
    initiator: 'USA',
    target: 'IRGC ballistic missile storage and launch sites, Kermanshah province',
    description: 'One of the strike areas identified in the initial US/Israeli targeting package. Western Iran provinces were among the most heavily struck — concentrated missile launcher sites along the Iraq border.',
    estimatedKIA: undefined,
    kiaNote: 'Casualties not confirmed.',
  },
  {
    id: 8,
    name: 'Tabriz — military airfields and IRGC',
    lat: 38.10,
    lng: 46.27,
    date: 'Feb 28, 2026',
    initiator: 'USA',
    target: 'Military airfields and IRGC installations, Tabriz (East Azerbaijan)',
    description: 'Strikes targeted military airfields and IRGC command infrastructure in northwestern Iran, part of the campaign that hit all 27 of Iran\'s provinces.',
    estimatedKIA: undefined,
    kiaNote: 'Casualties not confirmed.',
  },
  {
    id: 9,
    name: 'Shiraz — IRGC Aerospace Force',
    lat: 29.59,
    lng: 52.58,
    date: 'Feb 28, 2026',
    initiator: 'USA',
    target: 'IRGC Aerospace Force facilities, Shiraz',
    description: 'IRGC Aerospace Force drone and missile infrastructure in Shiraz struck. Part of the effort to destroy Iran\'s ~1,000 ballistic missiles pre-launch; ACLED estimated approximately 1,000 missiles were destroyed on the ground.',
    estimatedKIA: undefined,
    kiaNote: 'Casualties not confirmed.',
  },
  {
    id: 10,
    name: 'Bushehr — naval infrastructure',
    lat: 28.97,
    lng: 50.84,
    date: 'Feb 28, 2026',
    initiator: 'USA',
    target: 'IRGC Navy assets and coastal infrastructure, Bushehr',
    description: 'Strikes on IRGC naval infrastructure along the Persian Gulf coast. ACLED records 17 Iranian warships and 1 submarine destroyed during the campaign.',
    estimatedKIA: undefined,
    kiaNote: 'Casualties not confirmed.',
  },
  {
    id: 11,
    name: 'Minab girls\' school strike (disputed)',
    lat: 27.15,
    lng: 57.08,
    date: 'Mar 1, 2026',
    initiator: 'Israel',
    target: '"Shajareh Tayyebeh" elementary girls\' school, Minab, Hormozgan province',
    description: 'The deadliest single civilian strike of the campaign. Al Jazeera investigation found the targeting "likely deliberate." Israel and the US denied involvement. The school, "The Good Tree," was struck during class hours.',
    estimatedKIA: 165,
    kiaNote: '~165 schoolgirls and staff killed. Al Jazeera investigation raises questions over whether strike was deliberate.',
  },
  {
    id: 12,
    name: 'Jurf al-Nasr (PMF sites), Iraq',
    lat: 33.00,
    lng: 44.10,
    date: 'Feb 28, 2026',
    initiator: 'USA',
    target: 'Popular Mobilization Forces (PMF) positions, Jurf al-Nasr, southern Iraq',
    description: 'Limited US and Israeli airstrikes against Iran-backed PMF (Popular Mobilization Forces) sites in southern Iraq to suppress proxy launch capabilities.',
    estimatedKIA: 2,
    kiaNote: '2 PMF fighters killed, 5–7 wounded.',
  },

  // ── IRANIAN RETALIATORY STRIKES ───────────────────────────────────────────

  {
    id: 13,
    name: 'Iranian missile strike — Tel Aviv area',
    lat: 32.09,
    lng: 34.78,
    date: 'Feb 28, 2026',
    initiator: 'Iran',
    target: 'Tel Aviv metropolitan area, Israel',
    description: 'Iran launched ballistic missiles and drones at Israel within hours of the opening US-Israeli strikes. One Iranian missile struck a residential area in Tel Aviv; at least 40 buildings were damaged.',
    estimatedKIA: 1,
    kiaNote: '1 woman killed. 40+ buildings damaged.',
  },
  {
    id: 14,
    name: 'Iranian missile strike — Beit Shemesh',
    lat: 31.75,
    lng: 34.99,
    date: 'Mar 1, 2026',
    initiator: 'Iran',
    target: 'Residential area, Beit Shemesh, central Israel',
    description: 'A direct ballistic missile impact on a residential neighbourhood in Beit Shemesh caused the highest single-incident Israeli death toll of the campaign.',
    estimatedKIA: 9,
    kiaNote: '9 killed, 20+ wounded.',
  },
  {
    id: 15,
    name: 'Iranian strikes — Al Udeid Air Base, Qatar',
    lat: 25.12,
    lng: 51.31,
    date: 'Feb 28, 2026',
    initiator: 'Iran',
    target: 'Al Udeid Air Base (largest US air base in the region), Qatar',
    description: 'Iran launched 2 ballistic missiles and a drone at Al Udeid, the main US operational hub in the region. Missiles and drone were intercepted or caused limited damage. US confirmed 6 service members killed across Gulf bases overall.',
    estimatedKIA: 0,
    kiaNote: '0 at Al Udeid specifically. 6 US service members killed across Gulf bases (confirmed by Mar 2). 16 Qataris injured.',
  },
  {
    id: 16,
    name: 'Iranian strikes — US 5th Fleet HQ, Bahrain',
    lat: 26.21,
    lng: 50.60,
    date: 'Feb 28, 2026',
    initiator: 'Iran',
    target: 'US Navy 5th Fleet HQ (Juffair), Bahrain international airport, Manama residential areas',
    description: 'Iran struck multiple targets in Bahrain including the US 5th Fleet headquarters, the international airport, and residential buildings in Manama.',
    estimatedKIA: 1,
    kiaNote: '1 Asian worker killed, 4 injured.',
  },
  {
    id: 17,
    name: 'Iranian strikes — Kuwait (US facilities)',
    lat: 29.38,
    lng: 47.98,
    date: 'Feb 28 – Mar 4, 2026',
    initiator: 'Iran',
    target: 'US military facilities and oil infrastructure, Kuwait',
    description: 'Iran struck US military installations and oil infrastructure in Kuwait across several days. Several US warplanes crashed (crews survived) and 4 Kuwaiti civilians were killed.',
    estimatedKIA: 4,
    kiaNote: '4 killed, 35 injured. Several US aircraft lost.',
  },
  {
    id: 18,
    name: 'Iranian strikes — UAE',
    lat: 25.20,
    lng: 55.27,
    date: 'Feb 28, 2026',
    initiator: 'Iran',
    target: 'Abu Dhabi airport and landmark sites, UAE',
    description: 'Iran struck Abu Dhabi airport and landmark sites across the UAE. Three foreign nationals were killed.',
    estimatedKIA: 3,
    kiaNote: '3 killed (Pakistani, Nepali, Bangladeshi nationals), 78 injured.',
  },
  {
    id: 19,
    name: 'Iranian strikes — Jordan (intercepted)',
    lat: 31.95,
    lng: 35.93,
    date: 'Feb 28, 2026',
    initiator: 'Iran',
    target: 'Jordanian airspace / US assets, Jordan',
    description: 'Iran launched 49 drones and ballistic missiles at targets in Jordan. All were intercepted by Jordan\'s air defenses. 5 Jordanians were injured.',
    estimatedKIA: 0,
    kiaNote: '0 killed; 5 injured. All 49 projectiles intercepted.',
  },
  {
    id: 20,
    name: 'Iranian strikes — Duqm port & oil tanker, Oman',
    lat: 19.66,
    lng: 57.70,
    date: 'Mar 1–2, 2026',
    initiator: 'Iran',
    target: 'Duqm port and an oil tanker off Musandam, Oman',
    description: 'Iran struck Duqm port and an oil tanker off the coast of Musandam governorate — widening its retaliation to Oman despite Oman\'s traditional role as a back-channel diplomatic interlocutor.',
    estimatedKIA: 1,
    kiaNote: '1 killed, 5 injured.',
  },
  {
    id: 21,
    name: 'Iranian drone — UK RAF Akrotiri, Cyprus',
    lat: 34.59,
    lng: 32.99,
    date: 'Mar 1, 2026',
    initiator: 'Iran',
    target: 'RAF Akrotiri runway, UK Sovereign Base Area, Cyprus',
    description: 'An Iranian drone struck the runway at RAF Akrotiri in Cyprus, a UK sovereign military base. The attack was the westernmost strike of the campaign and demonstrated Iran\'s long-range drone reach.',
    estimatedKIA: 0,
    kiaNote: 'No fatalities. Runway damage.',
  },
  {
    id: 22,
    name: 'Iranian missiles — Erbil, Iraq (near US consulate)',
    lat: 36.19,
    lng: 44.01,
    date: 'Feb 28, 2026',
    initiator: 'Iran',
    target: 'Near US consulate and international airport, Erbil, Iraqi Kurdistan',
    description: 'Iran fired ballistic missiles at targets near the US consulate and Erbil international airport. All missiles were intercepted by US Patriot batteries.',
    estimatedKIA: 0,
    kiaNote: 'All missiles intercepted; no confirmed casualties.',
  },

  // ── HEZBOLLAH / LEBANON FRONT ─────────────────────────────────────────────

  {
    id: 23,
    name: 'Hezbollah missile & drone attacks — northern Israel',
    lat: 33.05,
    lng: 35.50,
    date: 'Mar 2, 2026',
    initiator: 'Hezbollah',
    target: 'Northern Israel (Galilee communities)',
    description: 'Hezbollah formally joined the war, launching its first missile and drone attacks on northern Israel since November 2024. A long-range missile was later fired at Tel Aviv on March 4.',
    estimatedKIA: undefined,
    kiaNote: 'Casualties not confirmed; heavy interceptions.',
  },
  {
    id: 24,
    name: 'Israeli strikes — Lebanon (Hezbollah retaliation)',
    lat: 33.39,
    lng: 35.49,
    date: 'Mar 2, 2026',
    initiator: 'Israel',
    target: 'Hezbollah rocket positions, tunnels, and command nodes, southern Lebanon',
    description: 'Israel launched over 250 retaliatory strikes across Lebanon targeting Hezbollah rocket and missile infrastructure. Strikes extended to the southern suburbs of Beirut (Dahiyeh). 4 family members were killed in a strike on Kfar Tebnit on March 4.',
    estimatedKIA: 77,
    kiaNote: '77 killed, 527 injured in Lebanon across the strike wave.',
  },
];
